### PR TITLE
Add CNAME

### LINKED ISSUE #78: Setup CNAME
1. Port [nwhacks2018_static](https://github.com/nwhacks/nwhacks2018_static) to [2018.nwhacks.io](https://2018.nwhacks.io)
2. ~~Setup CNAME in nwhacks2019 `/build` directory ([nwhacks.io](https://nwhacks.io)). Add compile to `/docs` command in Makefile and~~ configure CNAME for `/docs` directory ([nwhacks.io](https://nwhacks.io)).

### PR DESCRIPTION
**Pull request by chamkank**
:tickets: **Ticket(s)**: Closes #78 

---

## :construction_worker: Changes

Added CNAME file. This will set nwhacks.io to point to `/docs/`.

## :thought_balloon: Notes

**This should be merged in tandem with https://github.com/nwhacks/nwhacks2018_static/pull/91 to minimize downtime**. We should also make sure to build any new changes before merging new pull requests going forward.

### CODE REVIEW

**Comment by d4l3k** [comment]
@chamkank Do you have code to delete any existing service workers that might be cached from the old site? Just wondering how that fail over is going to happen for people that have the 2018 site cached in their browsers?

**Comment by chamkank** [comment]
@d4l3k Oh yikes I didn't even think about that, how would that work? Would it be similar to https://github.com/nwhacks/nwhacks2018_static/blob/8e38fe644e6dbc3e9bdfb248a86feb323ea9fdc9/index.html#L21-L61

**Comment by d4l3k** [comment]
More like
https://stackoverflow.com/questions/33704791/how-do-i-uninstall-a-service-worker

**Comment by d4l3k** [comment]
You could also register a new one to replace it instead of just removing
it. Old website had aggressive offline caching which was pretty nice for
schedules etc for international students without cell service

**Comment by chamkank** [comment]
Oh gotcha, I like the idea of replacing it instead of removing it. I can give it a shot this weekend

**Pull request merged**
